[package]
name = "proof-of-work-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
rayon = "1.7.0"
ring = "0.16.20"

[build.env]
passthrough = [
    "RUST_BACKTRACE"
]