[package]
name = "proof-of-work-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
rayon = "1.10.0"
ring = "0.17.8"

[build.env]
passthrough = [
    "RUST_BACKTRACE=1"
]